Repository GetA-BEER/GetABeer, pull requests merged in 2023-02, with the labels that each got.

#27 Fe/style/main/components
  fe/components/NavBar.tsx
  fe/components/inputs/BigInput.tsx
  fe/components/mainComponents/Advertise.tsx
  fe/components/mainComponents/BeerCategoryBtn.tsx
  fe/components/selectBox/PairingBox.tsx
  fe/components/selectBox/SortBox.tsx
  fe/components/smallCards/PopularBeer.tsx
  fe/components/smallCards/PopularBeerController.tsx
  fe/components/smallCards/SimilarBeer.tsx
  fe/components/smallCards/SimilarBeerController.tsx
  fe/components/smallCards/SmallCard.tsx
  fe/components/smallCards/SmallCardController.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallpairingController.tsx
  fe/pages/beer/PairingTitle.tsx
  fe/pages/beer/RatingTitle.tsx
  fe/pages/beer/index.tsx
  fe/pages/component/index.tsx
  fe/pages/index.tsx
  fe/pages/postpairing/ImageUpload.tsx
  fe/pages/postpairing/index.tsx
  fe/public/favicon.ico
  fe/public/images/background.png
  fe/public/next.svg
  fe/public/thirteen.svg
  fe/public/vercel.svg
Labels: feat, 안유진, front, style, fix

#31 GB-37 fix: 오타수정
  fe/components/beerPage/PairingTitle.tsx
  fe/pages/beer/index.tsx
Labels: 안유진, fix

#33 GB-27 feat & refactor: Rating
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/dto/RatingDto.java
  be/src/main/java/be/domain/rating/dto/RatingRequestDto.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/dto/RatingTagDto.java
  be/src/main/java/be/domain/rating/entity/RatingTag.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/rating/mapper/RatingTagMapper.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/service/RatingService.java
Labels: back, feat, 가 빈, refactor

#34 GB-38 style: 버튼 컴포넌트 수정, 인풋 컴포넌트 제작
  fe/components/button/CloseBtn.tsx
  fe/components/button/SubmitBtn.tsx
  fe/components/inputs/Input.tsx
  fe/pages/index.tsx
Labels: 성유미, front, style

#36 GB-27 feat & refactor & fix: 페어링 일대다 수정 및 페어링 페이지 조회 구현
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/controller/PairingController2.java
  be/src/main/java/be/domain/pairing/dto/PairingDto.java
  be/src/main/java/be/domain/pairing/dto/PairingImageDto.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/Pairing2.java
  be/src/main/java/be/domain/pairing/entity/PairingImage.java
  be/src/main/java/be/domain/pairing/entity/PairingImage2.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper2.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/PairingImageRepository2.java
  be/src/main/java/be/domain/pairing/repository/PairingRepository2.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/pairing/service/PairingService2.java
Labels: back, feat, 가 빈, refactor, fix

#37 GB-39 style: pairing 상세 페이지 제작
  fe/atoms/noReview.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/pairing/ImageCarousel.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/pairing/PairingCardController.tsx
  fe/components/pairing/ProfileCard.tsx
  fe/components/smallCards/SmallCard.tsx
  fe/components/smallCards/SmallCardController.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallpairingController.tsx
  fe/pages/beer/[id].tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/pairing/index.tsx
  fe/utils/timeFunc.tsx
Labels: feat, 안유진, front, style

#38 GB-40 style:로그인 페이지 제작
  fe/components/button/SubmitBtn.tsx
  fe/components/inputs/Input.tsx
  fe/components/login/Googlebtn.tsx
  fe/components/login/KakaoBtn.tsx
  fe/components/login/NaverBtn.tsx
  fe/pages/login/index.tsx
Labels: 성유미, front, style

#39 GB-41 feat: Implement Upload Image To S3
  be/build.gradle
  be/src/main/java/be/global/config/S3Config.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/java/be/global/image/ImageUploadController.java
  be/src/main/java/be/global/image/S3UploadService.java
  be/src/main/java/be/global/image/S3UploadServiceImpl.java
  be/src/main/resources/application.yml
Labels: back, feat, 가 빈, add, fix

#40 GB-27 refactor: Refactoring RatingService
  be/src/main/java/be/domain/rating/service/RatingService.java
Labels: back, 가 빈, refactor

#42 GB-45 stlye: editpairing 페이지 제작
  fe/components/Menu.tsx
  fe/components/NavBar.tsx
  fe/components/inputs/BigInput.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/pairing/PairingCardController.tsx
  fe/components/postPairingPage/ImageUpload.tsx
  fe/components/selectBox/PairingBox.tsx
  fe/components/wish/WishCard.tsx
  fe/pages/editpairing/index.tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/mypage/wish.tsx
  fe/pages/pairing/[id].tsx
  fe/public/images/beer-menu.png
Labels: 안유진, front, style

#46 GB-27 fix: 응답 바디 변경
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/dto/RatingTagDto.java
  be/src/main/java/be/domain/rating/entity/Rating.java
  be/src/main/java/be/domain/rating/entity/RatingTag.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/service/RatingService.java
Labels: back, 가 빈, fix

#47 GB-44 feat: Implement RatingComment
  be/src/main/java/be/domain/comment/controller/RatingCommentController.java
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/comment/entity/RatingComment.java
  be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/global/aop/GetABeerAop.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, feat, 가 빈

#48 GB-60 fix: URI api 추가
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
Labels: back, 가 빈, fix

#50 GB-50 feat: 통계 및 크롤링 준비
  be/src/main/java/be/domain/beer/controller/BeerController.java
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/beer/entity/BeerBeerCategory.java
  be/src/main/java/be/domain/beer/entity/BeerBeerTag.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsBestRating.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsCounts.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsStars.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsStatistics.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsTopTags.java
  be/src/main/java/be/domain/beer/entity/MonthlyBeer.java
  be/src/main/java/be/domain/beercategory/entity/BeerCategory.java
  be/src/main/java/be/domain/beertag/entity/BeerTag.java
  be/src/main/java/be/global/BaseTimeEntity.java
  be/src/main/java/be/global/aop/GetABeerAop.java
  be/src/main/java/be/global/aop/Pointcuts.java
  be/src/main/java/be/global/scheduler/BeerScheduler.java
  be/src/main/java/be/global/statistics/entity/BeerStatistics.java
  be/src/main/java/be/global/statistics/repository/BeerStatisticsJdbcRepository.java
  be/src/main/java/be/global/statistics/repository/BeerStatisticsQueryRepository.java
  be/src/main/java/be/global/statistics/repository/BeerStatisticsRepository.java
  be/src/main/java/be/global/statistics/service/StatisticsService.java
Labels: back, feat, 김태영, refactor, add, fix

#51 GB-44 feat & fix: Implement Comment
  be/src/main/java/be/domain/beertag/entity/BeerTag.java
  be/src/main/java/be/domain/comment/controller/PairingCommentController.java
  be/src/main/java/be/domain/comment/dto/PairingCommentDto.java
  be/src/main/java/be/domain/comment/entity/PairingComment.java
  be/src/main/java/be/domain/comment/mapper/PairingCommentMapper.java
  be/src/main/java/be/domain/comment/repository/PairingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/PairingCommentRepository.java
  be/src/main/java/be/domain/comment/repository/PairingCommentRepositoryImpl.java
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, feat, 가 빈, fix

#52 GB-60 fix: 평가와 유저 연동
  be/src/main/java/be/domain/comment/controller/RatingCommentController.java
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/comment/entity/RatingComment.java
  be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/dto/RatingRequestDto.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/entity/Rating.java
  be/src/main/java/be/domain/rating/entity/RatingTag.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/service/UserService.java
Labels: back, 가 빈, fix

#56 GB-59 fix: cors client local server, init userStatus 활동계정 고정
  be/src/main/java/be/global/init/Init.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
Labels: back, 서효진, fix

#55 Fe/style/components/beercard
  fe/components/inputs/BigInput.tsx
  fe/components/middleCards/MiddleCard.tsx
  fe/components/tag/ColorTag.tsx
  fe/components/tag/SmellTag.tsx
  fe/components/tag/TasteTag.tsx
  fe/components/tag/sparkleTag.tsx
  fe/pages/postrating/index.tsx
  fe/pages/test.tsx
  fe/react-rating-stars-component.d.ts
  fe/utils/TagMatcher.tsx
  fe/utils/ToDateString.tsx
Labels: 방세린, front, style

#60 GB-59 feat: 회원가입 시 태그, 카테고리 입력 및 수정가능
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/dto/UserDto.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/mapper/UserMapper.java
  be/src/main/java/be/domain/user/repository/UserBeerCategoryQRepository.java
  be/src/main/java/be/domain/user/repository/UserBeerTagQRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
Labels: back, feat, add

#61 GB-60 fix: 이미지, 평가, 코어스 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingImageDto.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/PairingImage.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/global/config/EmbeddedRedisConfig.java
  be/src/main/java/be/global/image/ImageHandler.java
  be/src/main/java/be/global/image/ImageUploadController.java
  be/src/main/java/be/global/image/PairingImageHandler.java
  be/src/main/java/be/global/image/S3UploadService.java
  be/src/main/java/be/global/image/S3UploadServiceImpl.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
  be/src/main/resources/static/docs/index.html
  be/src/test/java/be/GetABeerApplicationTests.java
  be/src/test/java/be/controller/BeerControllerRestDocs.java
Labels: back, 가 빈, fix

#64 GB-56 feat/main: 기능 구현
  fe/atoms/noReview.tsx
  fe/components/Menu.tsx
  fe/components/NavBar.tsx
  fe/components/beerPage/PairingTitle.tsx
  fe/components/beerPage/RatingTitle.tsx
  fe/components/mainPage/BeerCategoryBtn.tsx
  fe/components/modal/CameraModal.tsx
  fe/components/pairing/ImageCarousel.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/pairing/PairingCardController.tsx
  fe/components/postPairingPage/ImageUpload.tsx
  fe/components/signup/BeerCategory.tsx
  fe/components/smallCards/PopularBeer.tsx
  fe/components/smallCards/SimilarBeer.tsx
  fe/components/smallCards/SmallCard.tsx
  fe/components/smallCards/SmallCardController.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallTag.tsx
  fe/components/smallCards/SmallpairingController.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/beer/[id].tsx
  fe/pages/editpairing/index.tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/postpairing/index.tsx
  fe/styles/globals.css
  fe/tailwind.config.js
Labels: feat, 안유진, front, style

#65 fix/postPairing: 충돌해결
  fe/components/pairing/PairingCard.tsx
  fe/pages/editpairing/index.tsx
Labels: fix

#66 GB-69 feat: 소셜로그인
  be/build.gradle
  be/src/main/java/be/domain/beercategory/service/BeerCategoryService.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/entity/UserBeerCategory.java
  be/src/main/java/be/domain/user/entity/UserBeerTag.java
  be/src/main/java/be/domain/user/mapper/UserMapper.java
  be/src/main/java/be/domain/user/repository/UserRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/init/Init.java
  be/src/main/java/be/global/security/auth/filter/JwtAuthenticationFilter.java
  be/src/main/java/be/global/security/auth/filter/JwtVerificationFilter.java
  be/src/main/java/be/global/security/auth/handler/UserAccessDeniedHandler.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationEntryPoint.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationFailureHandler.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationSuccessHandler.java
  be/src/main/java/be/global/security/auth/jwt/JwtTokenizer.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/auth/oauth/service/CustomOAuth2UserService.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
  be/src/main/resources/application.yml
Labels: back, feat, 서효진, add, fix

#67 GB-61 feat: 추천 구현
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/like/controller/PairingLikeController.java
  be/src/main/java/be/domain/like/controller/RatingLikeController.java
  be/src/main/java/be/domain/like/entity/LikeStatus.java
  be/src/main/java/be/domain/like/entity/PairingLike.java
  be/src/main/java/be/domain/like/entity/RatingLike.java
  be/src/main/java/be/domain/like/repository/PairingLikeCustomRepository.java
  be/src/main/java/be/domain/like/repository/PairingLikeCustomRepositoryImpl.java
  be/src/main/java/be/domain/like/repository/PairingLikeRepository.java
  be/src/main/java/be/domain/like/repository/RatingLikeCustomRepository.java
  be/src/main/java/be/domain/like/repository/RatingLikeCustomRepositoryImpl.java
  be/src/main/java/be/domain/like/repository/RatingLikeRepository.java
  be/src/main/java/be/domain/like/service/PairingLikeService.java
  be/src/main/java/be/domain/like/service/RatingLikeService.java
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/entity/Rating.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/java/be/global/image/PairingImageHandler.java
Labels: back, feat, 가 빈

#71 GB-76 feat: 프로필 이미지 수정 및 삭제 구현
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/entity/ProfileImage.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/repository/ProfileImageRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/image/ImageHandler.java
  be/src/main/java/be/global/image/PairingImageHandler.java
Labels: back, feat, 서효진, add, fix

#73 GB-60 fix: 평가 및 페어링 조회 수정
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/PairingImage.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/entity/Rating.java
  be/src/main/java/be/domain/rating/entity/RatingTag.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, 가 빈, fix

#72 GB-77 feat: 마이페이지 나의 댓글 구현
  be/src/main/java/be/domain/comment/mapper/PairingCommentMapper.java
  be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java
  be/src/main/java/be/domain/comment/repository/PairingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/PairingCommentRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/service/UserService.java
Labels: back, feat, 서효진, add

#74 GB-78 feat: 소셜 로그인 시 임시 비밀번호 전송
  be/src/main/java/be/domain/mail/controller/MailController.java
  be/src/main/java/be/domain/mail/dto/MailDto.java
  be/src/main/java/be/domain/mail/service/MailService.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
Labels: back, feat, 서효진, add

#76 GB-60 fix: 페어링 업데이트 및 이미지 업데이트 수정, 유효성 추가
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/PairingImage.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/PairingImageCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingImageCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/PairingImageRepository.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/dto/RatingRequestDto.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/java/be/global/image/ImageHandler.java
  be/src/main/java/be/global/image/PairingImageHandler.java
Labels: back, 가 빈, refactor, fix

#77 GB-82 feat: Access Token & Refresh Token reissue
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/test/java/be/utils/BeerTestConstants.java
Labels: back, feat, 서효진, fix

#78 GB-83 refactoring
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/controller/UserPageController.java
  be/src/main/java/be/domain/user/service/UserPageService.java
  be/src/main/java/be/domain/user/service/UserPreferenceService.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/domain/user/service/pattern/StateButton.java
  be/src/main/java/be/domain/user/service/pattern/StatePattern.java
  be/src/main/java/be/global/image/ImageHandlerImpl.java
  be/src/main/java/be/global/security/auth/refresh/controller/RefreshTokenController.java
  be/src/main/java/be/global/security/auth/refresh/service/RefreshService.java
  be/src/main/java/be/global/security/auth/refresh/service/RefreshServiceImpl.java
Labels: back, 서효진, refactor, add, fix

#79 GB-83 fix
  be/src/main/java/be/domain/user/repository/UserRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
Labels: back, 서효진, refactor, fix

#80 GB-84 feat: Kafka 채팅 1차 구현
  be/build.gradle
  be/src/main/java/be/global/chat/KafkaConsumerService.java
  be/src/main/java/be/global/chat/KafkaProducerController.java
  be/src/main/java/be/global/chat/Message.java
  be/src/main/java/be/global/chat/config/KafkaConstants.java
  be/src/main/java/be/global/chat/config/ListenerConfiguration.java
  be/src/main/java/be/global/chat/config/ProducerConfiguration.java
  be/src/main/java/be/global/chat/config/WebSocketConfiguration.java
Labels: back, feat, 가 빈

#82 GB-56 fix/main: TimeFunc 재 적용
  fe/components/SpeechBalloon.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/smallCards/SmallCard.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/utils/TimeHandler.tsx
  fe/utils/timeFunc.tsx
Labels: 안유진, fix

#81 GB-61 fix: for 배포
  be/.DS_Store
  be/build.gradle
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/resources/application.yml
  be/src/main/resources/static/docs/index.html
Labels: back, 가 빈, 서효진, fix

#85 GB-61 fix: 화이트 라벨 방지 및 응답, 페이징 수정
  be/src/main/java/be/domain/comment/dto/PairingCommentDto.java
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/comment/mapper/PairingCommentMapper.java
  be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java
  be/src/main/java/be/domain/comment/repository/PairingCommentRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/like/controller/PairingLikeController.java
  be/src/main/java/be/domain/like/controller/RatingLikeController.java
  be/src/main/java/be/domain/like/dto/LikeResponseDto.java
  be/src/main/java/be/domain/like/service/PairingLikeService.java
  be/src/main/java/be/domain/like/service/RatingLikeService.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/global/home/HomeController.java
Labels: back, 가 빈, fix

#83 GB-83 fix: 닉네임 유효성 검사, 비밀번호 유효성 검사 수정
  be/src/main/java/be/domain/mail/controller/MailController.java
  be/src/main/java/be/domain/mail/service/MailService.java
  be/src/main/java/be/domain/user/dto/UserDto.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/mapper/UserMapper.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/init/Init.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/auth/oauth/service/CustomOAuth2UserService.java
Labels: back, 서효진, refactor, fix

#84 Fe/feat/rating
  fe/.env.development
  fe/.env.production
  fe/components/Header.tsx
  fe/components/NavBar.tsx
  fe/components/PageContainer.tsx
  fe/components/Pagenation.tsx
  fe/components/SearchModal.tsx
  fe/components/SearchSwiper.tsx
  fe/components/SpeechBalloon.tsx
  fe/components/Tag.tsx
  fe/components/inputs/CommentInput.tsx
  fe/components/inputs/StarRating.tsx
  fe/components/middleCards/BigCard.tsx
  fe/components/middleCards/MiddleCard.tsx
  fe/components/middleCards/MonthlyCard.tsx
  fe/components/middleCards/RatingCard.tsx
  fe/components/selectBox/SortBox.tsx
  fe/components/tag/CarbonationTag.tsx
  fe/components/tag/ColorTag.tsx
  fe/components/tag/SmellTag.tsx
  fe/components/tag/TasteTag.tsx
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/allrating/[beerid].tsx
  fe/pages/api/axios.ts
  fe/pages/editrating/[ratingid].tsx
  fe/pages/index.tsx
  fe/pages/monthly/index.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/postrating/index.tsx
  fe/pages/rating/[ratingid].tsx
  fe/pages/test.tsx
  fe/public/images/jejubeer.png
  fe/public/images/krin.jpeg
  fe/react-rating-stars-component.d.ts
  fe/utils/TagMatcher.tsx
Labels: 방세린, front, style

#91 GB-89 feat: 통계자료 작성 로직 변경 및 데이터 처리 기초 구현
  be/build.gradle
  be/src/main/java/be/GetABeerApplication.java
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/elasticsearch/entity/AnalysisBeer.java
  be/src/main/java/be/domain/elasticsearch/repository/BeerSearchCustomRepositoryImpl.java
  be/src/main/java/be/domain/elasticsearch/repository/BeerSearchRepository.java
  be/src/main/java/be/domain/elasticsearch/service/EsAutoCompleteService.java
  be/src/main/java/be/global/config/ElasticsearchConfig.java
  be/src/main/java/be/global/scheduler/GetABeerScheduler.java
  be/src/main/java/be/global/statistics/analysis/JTableSawController.java
  be/src/main/java/be/global/statistics/analysis/JTableSawService.java
  be/src/main/java/be/global/statistics/entity/BeerCategoryStatistics.java
  be/src/main/java/be/global/statistics/entity/BeerStatistics.java
  be/src/main/java/be/global/statistics/entity/BeerTagStatistics.java
  be/src/main/java/be/global/statistics/entity/PairingCategoryStatistics.java
  be/src/main/java/be/global/statistics/entity/TotalStatistics.java
  be/src/main/java/be/global/statistics/repository/BeerCategoryStatisticsQueryRepository.java
  be/src/main/java/be/global/statistics/repository/BeerTagStatisticsQueryRepository.java
  be/src/main/java/be/global/statistics/repository/PairingCategoryStatisticsQueryRepository.java
  be/test.csv
  be/test2.csv
Labels: setting, feat, 김태영, add

#88 GB-83 fix: 회원가입 유저 정보 입력 요청바디 형식 변경
  be/src/main/java/be/domain/user/dto/UserDto.java
  be/src/main/java/be/domain/user/mapper/UserMapper.java
Labels: back, 서효진, fix

#92 GB-61 fix: Rating And Pairing
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/PairingCategory.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/entity/RatingTag.java
  be/src/main/java/be/domain/rating/mapper/RatingTagMapper.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, 가 빈, fix

#95 GB-87: API 통신
  fe/.env.development
  fe/.env.production
  fe/components/NavBar.tsx
  fe/components/beerPage/BeerDetailCard.tsx
  fe/components/beerPage/KakaoShareButton.tsx
  fe/components/beerPage/PairingTitle.tsx
  fe/components/beerPage/RatingTitle.tsx
  fe/components/beerPage/StarScore.tsx
  fe/components/mainPage/BeerCategoryBtn.tsx
  fe/components/modal/CameraModal.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/pairing/PairingCardController.tsx
  fe/components/pairing/PairingImageCarousel.tsx
  fe/components/postPairingPage/ImageUpload.tsx
  fe/components/selectBox/PairingSelect.tsx
  fe/components/smallCards/PopularBeerController.tsx
  fe/components/smallCards/SimilarBeer.tsx
  fe/components/smallCards/SmallCardController.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallpairingController.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/_document.tsx
  fe/pages/allpairing/[id].tsx
  fe/pages/beer/[id].tsx
  fe/pages/editpairing/index.tsx
  fe/pages/index.tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/mypage/wish.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/pairing/index.tsx
  fe/pages/postpairing/index.tsx
  fe/public/images/example.png
  fe/styles/globals.css
  fe/utils/TimeHandler.tsx
Labels: feat, 안유진

#96 GB-92, 93, 94 rating 댓글 CRUD 및 마이페이지 rating, comment 구현
  fe/components/SpeechBalloon.tsx
  fe/components/inputs/CommentInput.tsx
  fe/components/middleCards/BigCard.tsx
  fe/components/middleCards/MiddleCard.tsx
  fe/components/middleCards/MonthlyCard.tsx
  fe/components/middleCards/RatingCard.tsx
  fe/components/selectBox/SortBox.tsx
  fe/pages/allrating/[beerid].tsx
  fe/pages/editrating/[ratingid].tsx
  fe/pages/mypage/comment.tsx
  fe/pages/mypage/rating.tsx
  fe/pages/postrating/index.tsx
  fe/pages/rating/[ratingid].tsx
  fe/pages/test.tsx
  fe/utils/BeerMatcher.tsx
Labels: feat, 방세린, front

#94 GB-83 feat/fix: oauth2 레디스 세션 도입
  be/build.gradle
  be/src/main/java/be/GetABeerApplication.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/repository/UserRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/config/RedisConfig.java
  be/src/main/java/be/global/security/auth/constant/SessionKey.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/auth/oauth/service/CustomOAuth2UserService.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/GoogleUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/KakaoUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/NaverUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/OAuth2UserInfo.java
  be/src/main/java/be/global/security/auth/session/SecuritySessionExpiredStrategy.java
  be/src/main/java/be/global/security/auth/userdetails/AuthUser.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
Labels: back, feat, 서효진, refactor, add, fix

#98 GB-96, GB-61 Deploy & fix : 환경변수 수정
  .github/workflows/gradle.yml
Labels: back, 가 빈, fix, deploy

#99 GB-60 fix: Rating Page 응답에 맥주 정보 추가
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/global/dto/MultiResponseDto.java
  be/src/main/java/be/global/dto/MultiResponseDtoWithBeerInfo.java
  be/src/main/java/be/global/dto/PageInfoWithBeerInfo.java
Labels: 가 빈, fix

#101 GB-83 feat/fix/refactor: wish 요청 기능 및 조회 구현
  be/src/main/java/be/domain/beer/controller/BeerController.java
  be/src/main/java/be/domain/beer/dto/BeerDto.java
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/beer/mapper/BeerMapper.java
  be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java
  be/src/main/java/be/domain/beer/service/BeerService.java
  be/src/main/java/be/domain/beer/service/BeerServiceImpl.java
  be/src/main/java/be/domain/beerwishlist/controller/BeerWishlistController.java
  be/src/main/java/be/domain/beerwishlist/dto/BeerWishlistDto.java
  be/src/main/java/be/domain/beerwishlist/entity/BeerWishlist.java
  be/src/main/java/be/domain/beerwishlist/mapper/BeerWishlistMapper.java
  be/src/main/java/be/domain/beerwishlist/repository/BeerWishListQRepository.java
  be/src/main/java/be/domain/beerwishlist/repository/BeerWishlistRepository.java
  be/src/main/java/be/domain/beerwishlist/service/BeerWishlistService.java
  be/src/main/java/be/domain/beerwishlist/service/BeerWishlistServiceImpl.java
  be/src/main/java/be/domain/beerwishlist/service/pattern/WishButton.java
  be/src/main/java/be/domain/beerwishlist/service/pattern/WishState.java
  be/src/main/java/be/domain/comment/repository/PairingCommentRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/user/controller/UserPageController.java
  be/src/main/java/be/domain/user/service/UserService.java
Labels: back, feat, 서효진, refactor, add, fix

#103 GB-96 Deploy : Gradle 수정 및 배포 스크립트 작성 및 앱 스펙 작성
  .github/workflows/gradle.yml
  appspec.yml
  scripts/start.sh
Labels: back, 가 빈, deploy

#104 GB-83 fix
  be/src/main/java/be/domain/mail/controller/MailController.java
  be/src/main/java/be/domain/mail/service/MailService.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/auth/oauth/service/CustomOAuth2UserService.java
  be/src/main/java/be/global/security/auth/session/annotation/LoginOAuth2User.java
  be/src/main/java/be/global/security/auth/session/controller/SessionController.java
  be/src/main/java/be/global/security/auth/session/resolver/LoginOAuth2UserArgumentResolver.java
  be/src/main/java/be/global/security/auth/session/user/SessionUser.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
Labels: back, feat, 서효진, refactor, add, fix

#105 GB-60 fix: user 로그인으로 수정
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/controller/RatingController.java
  be/src/main/java/be/domain/rating/dto/RatingRequestDto.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, fix

#119 GB-87 feat: 자잘한 작업
  fe/components/WishHeart.tsx
  fe/components/beerPage/BeerDetailCard.tsx
  fe/components/beerPage/KakaoShareButton.tsx
  fe/components/postPairingPage/PostDetailCard.tsx
  fe/pages/allpairing/[id].tsx
Labels: 안유진

#128 GB-60 fix & feat & refactor : 페어링 조회 수정, 레이팅 응답 필드 추가
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/entity/CategoryHelper.java
  be/src/main/java/be/domain/pairing/entity/PairingCategory.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/image/PairingImageCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/image/PairingImageCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/image/PairingImageRepository.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/pairing/service/helper/GetAllUserNotNull.java
  be/src/main/java/be/domain/pairing/service/helper/GetAllUserNull.java
  be/src/main/java/be/domain/pairing/service/helper/GetCategoryUserNotNull.java
  be/src/main/java/be/domain/pairing/service/helper/GetCategoryUserNull.java
  be/src/main/java/be/domain/pairing/service/helper/PairingState.java
  be/src/main/java/be/domain/pairing/service/helper/StateHelper.java
  be/src/main/java/be/domain/rating/dto/RatingResponseDto.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
  be/src/main/java/be/global/config/RedisConfig.java
  be/src/main/java/be/global/image/ImageHandlerImpl.java
  be/src/main/java/be/global/init/Init.java
Labels: back, feat, 가 빈, refactor, fix

#129 GB-60 fix: 파일 required 추가 및 DTO required 제거
  be/src/main/java/be/domain/pairing/controller/PairingController.java
Labels: back, 가 빈, fix

#131 GB-60 fix: 응답 바디 및 본인 추천 가능하게 수정
  be/src/main/java/be/domain/like/service/PairingLikeService.java
  be/src/main/java/be/domain/like/service/RatingLikeService.java
  be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/global/config/RedisConfig.java
Labels: back, 가 빈, fix

#106 GB-60 Deploy : update gradle.yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, deploy

#134 GB-60 fix: 개수 180개 수정 및 주석 제거
  be/src/main/java/be/global/init/Init.java
Labels: back, 가 빈, refactor, fix

#135 GB-96 Deploy: Update yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, fix, deploy

#136 GB-60 fix: 배포용 cors 주석 변경 및 댓글 userId 입력 삭제
  be/src/main/java/be/domain/comment/controller/PairingCommentController.java
  be/src/main/java/be/domain/comment/controller/RatingCommentController.java
  be/src/main/java/be/domain/comment/dto/PairingCommentDto.java
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
Labels: back, 가 빈, fix

#138 GB-60 fix: appspec위치 변경 및 pairing 에러 해결
  .DS_Store
  be/.DS_Store
  be/appspec.yml
  be/src/main/java/be/domain/pairing/controller/PairingController.java
Labels: back, 가 빈, fix, deploy

#140 GB-96 fix: appspec yaml로 변경
  appspec.yaml
Labels: back, 가 빈, fix, deploy

#142 GB-83 fix: Set-Cookie -> Cookie
  be/src/main/java/be/global/security/auth/refresh/service/RefreshServiceImpl.java
Labels: 서효진, fix

#145 GB-96 Deploy: update yml
  appspec.yml
  be/appspec.yml
Labels: back, 가 빈, fix, deploy

#148 GB-96 Deploy: Update yml
  appspec.yml
Labels: back, 가 빈, fix, deploy

#150 GB-60 fix: imageUrl -> userImage
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
Labels: back, 서효진, fix

#153 GB-96 Deploy: Update yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, fix, deploy

#154 GB-83 fix: 소셜 로그인 리다이렉트 url 로컬로 변경
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
Labels: back, 서효진, fix

#156 GB-96 Deploy :Update yml
  .github/workflows/gradle.yml
  be/appspec.yml
Labels: back, 가 빈, deploy

#155 GB-60 fix: 평가 및 댓글 관련 수정
  be/src/main/java/be/domain/comment/dto/RatingCommentDto.java
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/domain/rating/service/RatingService.java
Labels: back, 가 빈, fix

#159 GB-96 Deploy: Update yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, deploy

#160 GB-96 Deploy : yml 위치 변경
  .DS_Store
  appspec.yml
  be/.DS_Store
  scripts/start.sh
Labels: back, 가 빈, deploy

#161 GB-83 fix: 소셜로그인 리다이렉트 URL 서버로 변경
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
Labels: back, 서효진, fix

#162 GB-96 Deploy : Update yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, deploy

#163 GB-60 refactor: 필요없는 주석 제거 및 Redis 설정 삭제
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/global/config/RedisConfig.java
Labels: back, 가 빈, refactor

#165 GB-96 Deploy: Update shell
  scripts/start.sh
Labels: back, 가 빈, deploy

#166 GB-60 refactor : 프로파일 액티브 중복으로 삭제
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, refactor

#167 GB-96 Deploy: update shell
  scripts/start.sh
Labels: back, 가 빈, fix, deploy

#168 GB-60 refacotr : 필요없는 임포트 삭제
  be/src/main/java/be/domain/comment/mapper/PairingCommentMapper.java
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/like/controller/RatingLikeController.java
  be/src/main/java/be/domain/like/service/PairingLikeService.java
  be/src/main/java/be/domain/like/service/RatingLikeService.java
Labels: back, 가 빈, refactor

#169 GB-96 Deploy: Update yml
  .github/workflows/gradle.yml
Labels: back, deploy

#170 GB-96 Deploy: Update shell
  scripts/start.sh
Labels: back, 가 빈, fix, deploy

#171 GB-60 refacotr: 폴더 정리
  be/src/main/java/be/domain/comment/repository/pairing/PairingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/pairing/PairingCommentRepository.java
  be/src/main/java/be/domain/comment/repository/pairing/PairingCommentRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/rating/RatingCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/rating/RatingCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/rating/RatingCommentRepository.java
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/user/service/UserPageService.java
Labels: back, 가 빈, refactor

#172 GB-96 Deploy: Update shell
  scripts/start.sh
Labels: back, deploy

#173 GB-84 feat: 채팅방 유저 매핑
  be/src/main/java/be/domain/chatting/entity/ChatRoom.java
  be/src/main/java/be/domain/user/entity/User.java
Labels: back, feat, 가 빈

#174 GB-96 Deploy:Update Shell
  scripts/start.sh
Labels: back, deploy

#175 GB-83 fix: 리다이렉트 변경
  be/src/main/java/be/global/security/auth/oauth/RedirectController.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
Labels: back, 서효진, fix

#178 GB-60 add: 플레인 생성 방지 추가
  be/build.gradle
Labels: back, 가 빈, add

#180 GB-71 feat: 소셜로그인 구현
  fe/.env.development
  fe/.env.production
  fe/components/button/BackPageBtn.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/signup/BeerCategory.tsx
  fe/next.config.js
  fe/pages/login/index.tsx
  fe/pages/myedit/index.tsx
  fe/pages/mypage/index.tsx
  fe/pages/pwedit/index.tsx
  fe/pages/signup/email.tsx
  fe/pages/signup/index.tsx
  fe/pages/signup/information.tsx
Labels: 성유미

#185 GB-96 Deploy : main으로 브랜치 변경
  .github/workflows/gradle.yml
Labels: back, 가 빈, deploy

#186 GB-83 fix: 페이지네이션, 소셜로그인 리다이렉트 무한루프
  be/src/main/java/be/domain/beerwishlist/controller/BeerWishlistController.java
  be/src/main/java/be/domain/beerwishlist/mapper/BeerWishlistMapper.java
  be/src/main/java/be/domain/beerwishlist/repository/BeerWishListQRepository.java
  be/src/main/java/be/domain/beerwishlist/service/BeerWishlistService.java
  be/src/main/java/be/domain/beerwishlist/service/BeerWishlistServiceImpl.java
  be/src/main/java/be/domain/beerwishlist/service/pattern/WishState.java
  be/src/main/java/be/domain/comment/mapper/PairingCommentMapper.java
  be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/rating/mapper/RatingMapper.java
  be/src/main/java/be/domain/user/controller/UserPageController.java
  be/src/main/java/be/domain/user/dto/MyPageMultiResponseDto.java
  be/src/main/java/be/global/security/auth/oauth/RedirectController.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
Labels: back, 서효진, fix

#187 GB-96 Deploy : Update yml
  .github/workflows/gradle.yml
Labels: back, deploy

#190 GB-60 fix: 채팅 수정 및 홈 수정
  be/src/main/java/be/domain/chatting/entity/ChatMessage.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/global/chat/ChatRoom.java
  be/src/main/java/be/global/chat/Message.java
  be/src/main/java/be/global/home/HomeController.java
Labels: back, 가 빈, fix

#191 GB-60 fix: home 주소
  be/src/main/java/be/global/home/HomeController.java
Labels: back, 가 빈, fix
