Repository GetA-BEER/GetABeer, pull requests merged in 2023-03, with the labels that each got.

#193 GB-105 feat: 알림 기능 구현
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/domain/follow/FollowService.java
  be/src/main/java/be/domain/notice/controller/NotificationController.java
  be/src/main/java/be/domain/notice/dto/NotificationDto.java
  be/src/main/java/be/domain/notice/entity/Notification.java
  be/src/main/java/be/domain/notice/entity/NotificationType.java
  be/src/main/java/be/domain/notice/repository/EmitterRepository.java
  be/src/main/java/be/domain/notice/repository/NotificationRepository.java
  be/src/main/java/be/domain/notice/service/NotificationService.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, feat, 서효진, add

#194 GB-83 fix: oauth2 / feat: discord logging
  .github/workflows/gradle.yml
  be/build.gradle
  be/src/main/java/be/domain/mail/controller/MailController.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/user/controller/UserController.java
  be/src/main/java/be/domain/user/entity/User.java
  be/src/main/java/be/domain/user/repository/UserRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/aop/DiscordWebhook.java
  be/src/main/java/be/global/aop/LoggingToDiscord.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationEntryPoint.java
  be/src/main/java/be/global/security/auth/oauth/CustomOAuth2User.java
  be/src/main/java/be/global/security/auth/oauth/RedirectController.java
  be/src/main/java/be/global/security/auth/oauth/attributes/OAuth2Attribute.java
  be/src/main/java/be/global/security/auth/oauth/authentication/CustomAuthentication.java
  be/src/main/java/be/global/security/auth/oauth/controller/OAuth2Controller.java
  be/src/main/java/be/global/security/auth/oauth/dto/OAuthDto.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2FailureHandler.java
  be/src/main/java/be/global/security/auth/oauth/handler/OAuth2SuccessHandler.java
  be/src/main/java/be/global/security/auth/oauth/service/CustomOAuth2UserService.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/NaverUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/strategy/userinfo/OAuth2UserInfo.java
  be/src/main/java/be/global/security/auth/oauth/userinfo/GoogleUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/userinfo/KakaoUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/userinfo/NaverUserInfo.java
  be/src/main/java/be/global/security/auth/oauth/userinfo/OAuth2UserInfo.java
  be/src/main/java/be/global/security/auth/userdetails/AuthUser.java
  be/src/main/java/be/global/security/config/SecurityConfig.java
  be/src/main/java/be/global/security/config/WebMvcConfig.java
  be/src/main/resources/application-dev.yml
  be/src/main/resources/application.yml
  be/src/main/resources/logback-spring.xml
Labels: back, 서효진, refactor, fix

#199 GB-60 feat: discord 서버 실행 확인
  .github/workflows/gradle.yml
  be/src/main/java/be/global/aop/LoggingToDiscord.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationEntryPoint.java
  be/src/main/resources/application-dev.yml
Labels: back, 서효진, logger

#203 GB-96 Deploy: update 스크립트
  scripts/start.sh
Labels: back, 가 빈, deploy

#204 GB-83 remove : xml
  be/src/main/resources/application-dev.yml
Labels: 서효진

#205 GB-83 remove: property
  be/src/main/java/be/domain/mail/config/MailConfig.java
Labels: back, 서효진

#206 GB-98 feat:알림 기능 및 HEIC이미지 변환 기능 구현
  fe/components/Alarm.tsx
  fe/components/Header.tsx
  fe/components/SpeechBalloon.tsx
  fe/components/beerPage/PairingTitle.tsx
  fe/components/beerPage/RatingTitle.tsx
  fe/components/editPairingPage/EditImage.tsx
  fe/components/mainPage/BeerCategoryBtn.tsx
  fe/components/modal/CameraModal.tsx
  fe/components/postPairingPage/ImageUpload.tsx
  fe/components/postPairingPage/Loading.tsx
  fe/components/smallCards/PopularBeer.tsx
  fe/components/smallCards/RecommendBeer.tsx
  fe/components/smallCards/SimilarBeer.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallRatingCard.tsx
  fe/components/wish/WishCard.tsx
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/pages/beer/[id].tsx
  fe/pages/editpairing/[id].tsx
  fe/pages/index.tsx
  fe/pages/mypage/wish.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/pairingTest.tsx
  fe/pages/postpairing/index.tsx
  fe/tailwind.config.js
  fe/yarn.lock
Labels: feat, 안유진, style, fix

#210 GB-96 Deploy: update gradle.yml
  .github/workflows/gradle.yml
Labels: back, 가 빈, deploy

#211 GB-96 add: RDS 연결
  be/build.gradle
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, add

#212 GB-60 feat: discord logging
  be/build.gradle
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/resources/logback.xml
Labels: back, 서효진, add, logger

#214 GB-96 fix: build, yml
  be/build.gradle
Labels: back, 가 빈, deploy

#221 GB-108 style: 채팅방 및 신고하기 버튼 스타일 만들기
  fe/components/Chat.tsx
  fe/components/ChatBalloon.tsx
  fe/components/SpeechBalloon.tsx
  fe/components/button/BackPageBtn.tsx
  fe/components/inputs/CommentInput.tsx
  fe/components/mainPage/BeerCategoryBtn.tsx
  fe/components/middleCards/RatingCard.tsx
  fe/components/pairing/DetailCard.tsx
  fe/pages/_app.tsx
  fe/pages/login/index.tsx
  fe/pages/mypage/index.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/signup/information.tsx
  fe/pages/signup/oauthInformation.tsx
  fe/utils/SearchMatcher.tsx
Labels: 방세린, front, style

#222 GB-96 & GB-60 fix : Docker Deploy 수정 및 서버 배포 중 오류 수정, RDS 연결
  .DS_Store
  .github/workflows/gradle.yml
  be/build.gradle
  be/src/main/java/be/domain/comment/service/PairingCommentService.java
  be/src/main/java/be/domain/comment/service/RatingCommentService.java
  be/src/main/java/be/domain/like/service/PairingLikeService.java
  be/src/main/java/be/domain/like/service/RatingLikeService.java
  be/src/main/java/be/domain/pairing/service/helper/StateHelper.java
  be/src/main/java/be/global/image/ImageHandlerImpl.java
  be/src/main/java/be/global/init/Init.java
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, deploy

#226 GB-83 fix: 프로필이미지, 위시리스트, 디코 에러 모니터링
  be/build.gradle
  be/src/main/java/be/domain/beerwishlist/service/BeerWishlistServiceImpl.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/domain/user/service/pattern/EditImage.java
  be/src/main/java/be/domain/user/service/pattern/FirstEditImage.java
  be/src/main/java/be/domain/user/service/pattern/StateButton.java
  be/src/main/java/be/domain/user/service/pattern/StatePattern.java
  be/src/main/java/be/global/aop/DiscordWebhook.java
  be/src/main/java/be/global/discord/DiscordAppender.java
  be/src/main/java/be/global/discord/LoggingToDiscord.java
  be/src/main/java/be/global/security/auth/handler/UserAuthenticationEntryPoint.java
  be/src/main/resources/logback.xml
Labels: back, feat, 서효진, add, fix, logger

#225 GB-98 chore: 디자인 수정
  fe/components/Chat.tsx
  fe/components/NavBar.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/share/ShareBtn.tsx
  fe/pages/_app.tsx
  fe/pages/allpairing/[id].tsx
  fe/pages/beer/[id].tsx
  fe/pages/editpairing/[id].tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/mypage/wish.tsx
  fe/pages/pairing/[id].tsx
Labels: 안유진

#230 GB-60 feat: discord error monitoring
  be/build.gradle
  be/src/main/java/be/global/discord/DiscordAppender.java
  be/src/main/java/be/global/discord/LoggingToDiscord.java
  be/src/main/resources/logback.xml
Labels: back, feat, 서효진, add, fix, logger

#232 GB-60 fix: 배포 과정에 발견한 수정사항
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsBestRating.java
  be/src/main/java/be/domain/beerwishlist/entity/BeerWishlist.java
  be/src/main/java/be/domain/rating/entity/Rating.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/global/home/HomeController.java
  be/src/main/resources/templates/favicon.ico
  be/src/main/resources/templates/home.html
Labels: back, 가 빈, fix

#245 GB-110 fix: 수정 사항 반영
  be/build.gradle
  be/src/main/java/be/domain/follow/FollowService.java
  be/src/main/java/be/domain/notice/dto/NotificationDto.java
  be/src/main/java/be/domain/notice/entity/Notification.java
  be/src/main/java/be/domain/notice/service/NotificationService.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: back, 서효진

#248 GB-109 deploy : 도커 자동배포 및 배포 과정 자잘한 수정과 더미데이터 추가
  .github/workflows/deploy.yml
  be/Dockerfile
  be/docker-compose.yml
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/global/init/Init.java
  be/src/main/resources/Get_A_Beer_Products.csv
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, add, fix, deploy

#247 fix: 채팅 공백 보내기 방지 및 자동 스크롤다운 적용
  fe/components/Chat.tsx
  fe/components/Header.tsx
  fe/components/NavBar.tsx
  fe/components/middleCards/MiddleCard.tsx
  fe/components/middleCards/MonthlyCard.tsx
  fe/components/middleCards/RatingCard.tsx
  fe/components/middleCards/SearchCard.tsx
  fe/components/modal/CameraModal.tsx
  fe/components/postPairingPage/Loading.tsx
  fe/components/postPairingPage/PostDetailCard.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/404.tsx
  fe/pages/monthly/index.tsx
  fe/pages/search/image.tsx
  fe/pages/search/index.tsx
  fe/pages/userpage/[id].tsx
  fe/yarn.lock
Labels: 방세린, front, add, fix

#254 GB-109 fix: json 문제 수정 및 카프카 주석
  .github/workflows/deploy.yml
  be/build.gradle
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, fix, deploy

#257 GB-109 fix: json 파일
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, fix, deploy

#256 GB-98 chore: config 추가
  fe/components/Alarm.tsx
  fe/pages/allpairing/[id].tsx
  fe/pages/api/axios.ts
  fe/pages/beer/[id].tsx
  fe/pages/editpairing/[id].tsx
  fe/pages/index.tsx
  fe/pages/mypage/pairing.tsx
  fe/pages/pairing/[id].tsx
Labels: 안유진, add

#259 GB-109 fix : json 원래대로
  .github/workflows/deploy.yml
  be/src/main/resources/application-dev.yml
Labels: back, 가 빈, fix, deploy

#262 GB-109 deploy : update yml
  .github/workflows/deploy.yml
Labels: back, 가 빈, fix, deploy

#263 GB-109 deploy : json 변경 제발 최종
  .github/workflows/deploy.yml
  be/src/main/resources/application-dev.yml
Labels: back, fix, deploy

#267 chore: axios config 추가
  fe/components/PairingThumbs.tsx
  fe/components/SpeechBalloon.tsx
  fe/components/WishHeart.tsx
  fe/components/middleCards/RatingCard.tsx
  fe/components/pairing/DetailCard.tsx
  fe/components/pairing/PairingCard.tsx
  fe/components/smallCards/SmallRatingCard.tsx
  fe/pages/editrating/[ratingid].tsx
  fe/pages/mypage/comment.tsx
  fe/pages/mypage/rating.tsx
  fe/pages/postrating/index.tsx
  fe/pages/rating/[ratingid].tsx
Labels: 방세린, front, add

#268 GB-106 style: 페이지 아래 패딩 수정
  fe/components/followPage/FollowBtn.tsx
  fe/pages/allpairing/[id].tsx
  fe/pages/beer/[id].tsx
  fe/pages/follower/[id].tsx
  fe/pages/following/[id].tsx
  fe/pages/index.tsx
  fe/pages/pairing/[id].tsx
  fe/pages/pwedit/index.tsx
  fe/pages/search/index.tsx
  fe/pages/userpage/[id].tsx
Labels: 성유미, front, style

#269 GB-98 chore: 글자 크기 수정
  fe/components/pairing/DetailCard.tsx
  fe/components/postPairingPage/PostDetailCard.tsx
  fe/components/smallCards/SmallPairingCard.tsx
  fe/components/smallCards/SmallRatingCard.tsx
Labels: 안유진, add

#271 GB-110 feat: notification , fix: UserPage PageInfo
  be/src/main/java/be/domain/notice/controller/NotificationController.java
  be/src/main/java/be/domain/notice/repository/NotificationQRepository.java
  be/src/main/java/be/domain/notice/service/NotificationService.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java
Labels: back, feat, 서효진, fix

#272 GB-60 fix: rating delete
  be/src/main/java/be/domain/rating/service/RatingService.java
Labels: back, 가 빈, fix

#284 GB-60 fix: 회원가입시 채팅방 생성 및 Rating 수정
  be/src/main/java/be/domain/chat/redis/controller/RedisChatController.java
  be/src/main/java/be/domain/chat/redis/repository/RedisChatRepository.java
  be/src/main/java/be/domain/chat/redis/service/RedisRoomService.java
  be/src/main/java/be/domain/rating/service/RatingService.java
  be/src/main/java/be/domain/user/repository/UserQueryRepository.java
  be/src/main/java/be/domain/user/service/UserService.java
  be/src/main/java/be/global/aop/ChatAop.java
  be/src/main/java/be/global/aop/Pointcuts.java
Labels: back, 가 빈, fix

#286 GB-110 fix: notification endpoint
  be/src/main/java/be/domain/notice/controller/NotificationController.java
Labels: back, 서효진, fix

#287 GB-106 fix: 토큰 재발급 수정, chore: 검색페이지 로딩 추가
  fe/components/Header.tsx
  fe/pages/login/index.tsx
  fe/pages/search/index.tsx
Labels: 성유미, front, fix

#289 GB-60 fix: 채팅방 자동 생성 및 채팅방 생성 AOP 및 채팅방 내용 수정
  be/build.gradle
  be/src/main/java/be/domain/chat/redis/controller/RedisChatController.java
  be/src/main/java/be/domain/chat/redis/dto/RedisMessageDto.java
  be/src/main/java/be/domain/chat/redis/entity/ChatType.java
  be/src/main/java/be/domain/chat/redis/entity/RedisChat.java
  be/src/main/java/be/domain/chat/redis/entity/RedisChatMessage.java
  be/src/main/java/be/domain/chat/redis/entity/RedisChatRoom.java
  be/src/main/java/be/domain/chat/redis/repository/RedisChatRepository.java
  be/src/main/java/be/domain/chat/redis/service/RedisChatService.java
  be/src/main/java/be/domain/chat/redis/service/RedisRoomService.java
  be/src/main/java/be/global/aop/ChatAop.java
  be/src/main/java/be/global/aop/Pointcuts.java
  be/src/main/java/be/global/init/Init.java
Labels: back, 가 빈, fix

#291 GB-60 fix: aop 채팅방 수정
  be/src/main/java/be/global/aop/ChatAop.java
Labels: back, 가 빈, fix

#292 GB-60 fix: message 리스트 가져오기 수정
  be/src/main/java/be/domain/chat/redis/dto/RedisMessageDto.java
Labels: back, 가 빈, fix

#294 GB-110 fix: user role 변경
  be/src/main/java/be/global/security/auth/utils/CustomAuthorityUtils.java
Labels: back, 서효진, fix

#295 GB-60 fix: aop 채팅방 수정
  be/src/main/java/be/global/aop/ChatAop.java
Labels: back, 가 빈, fix

#296 GB-60 fix: 채팅방 AOP 수정
  be/src/main/java/be/global/aop/ChatAop.java
Labels: back, 가 빈, fix

#301 GB-60 fix: 관리자 추가 및 메세지 요청 시 유저 아이디로
  be/src/main/java/be/domain/chat/redis/controller/RedisChatController.java
  be/src/main/java/be/domain/chat/redis/dto/RedisMessageDto.java
  be/src/main/java/be/domain/chat/redis/entity/RedisChatMessage.java
  be/src/main/java/be/domain/chat/redis/entity/RedisChatRoom.java
  be/src/main/java/be/domain/chat/redis/repository/RedisChatRepository.java
  be/src/main/java/be/domain/chat/redis/service/RedisChatService.java
Labels: back, 가 빈, fix

#306 main 페이지 SSR 적용
  fe/components/Alarm.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/api/useFetch.ts
  fe/pages/beer/[id].tsx
  fe/pages/index.tsx
  fe/yarn.lock
Labels: 안유진, front, add
