Repository GetA-BEER/GetABeer, pull requests merged in 2023-01, with the labels that each got.

#3 FE 초기 세팅
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/postcss.config.js
  fe/public/favicon.ico
  fe/public/next.svg
  fe/public/thirteen.svg
  fe/public/vercel.svg
  fe/src/pages/_app.tsx
  fe/src/pages/_document.tsx
  fe/src/pages/api/hello.ts
  fe/src/pages/index.tsx
  fe/src/styles/Home.module.css
  fe/src/styles/globals.css
  fe/tailwind.config.js
  fe/tsconfig.json
Labels: setting, front

#6 GB-22:FE초기 개발환경 세팅
  fe/src/pages/atoms/examples.tsx
Labels: setting, front

#5 GB-16 fix : Query DSL 버전 변경
  be/build.gradle
Labels: setting, back, 김태영, add

#7 GB-22 style: 폴더구조 정리
  fe/atoms/examples.tsx
  fe/pages/_app.tsx
  fe/pages/_document.tsx
  fe/pages/api/hello.ts
  fe/pages/index.tsx
  fe/pages/main/index.tsx
  fe/public/images/adv.jpg
  fe/styles/Home.module.css
  fe/styles/globals.css
Labels: setting, 안유진, front, add

#9 GB-23 feat: 댓글 관련 및 채팅 관련 엔티티 구현 및 연관관계 매핑
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/chatting/entity/ChatMessage.java
  be/src/main/java/be/domain/chatting/entity/ChatRoom.java
  be/src/main/java/be/domain/comment/entity/BeerComment.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/entity/PairingCategory.java
  be/src/main/java/be/domain/pairing/entity/PairingImage.java
  be/src/main/java/be/domain/recomment/entity/BeerRecomment.java
  be/src/main/java/be/domain/recomment/entity/PairingRecomment.java
Labels: back, feat, 가 빈

#10 GB-23 feat: Comment 관련 기본 틀 구현 및 Pairing 구현
  be/src/main/java/be/domain/comment/controller/BeerCommentController.java
  be/src/main/java/be/domain/comment/dto/BeerCommentDto.java
  be/src/main/java/be/domain/comment/entity/BeerComment.java
  be/src/main/java/be/domain/comment/mapper/BeerCommentMapper.java
  be/src/main/java/be/domain/comment/repository/BeerCommentCustomRepository.java
  be/src/main/java/be/domain/comment/repository/BeerCommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/comment/repository/BeerCommentRepository.java
  be/src/main/java/be/domain/comment/service/BeerCommentService.java
  be/src/main/java/be/domain/pairing/controller/PairingController.java
  be/src/main/java/be/domain/pairing/dto/PairingDto.java
  be/src/main/java/be/domain/pairing/entity/Pairing.java
  be/src/main/java/be/domain/pairing/mapper/PairingMapper.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java
  be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java
  be/src/main/java/be/domain/pairing/repository/PairingRepository.java
  be/src/main/java/be/domain/pairing/service/PairingService.java
  be/src/main/java/be/domain/recomment/controller/BeerRecommentController.java
  be/src/main/java/be/domain/recomment/controller/PairingRecommentController.java
  be/src/main/java/be/domain/recomment/dto/BeerRecommentDto.java
  be/src/main/java/be/domain/recomment/dto/ParingRecommentDto.java
  be/src/main/java/be/domain/recomment/mapper/BeerRecommentMapper.java
  be/src/main/java/be/domain/recomment/mapper/PairingRecommentMapper.java
  be/src/main/java/be/domain/recomment/repository/BeerRecommentCustomRepository.java
  be/src/main/java/be/domain/recomment/repository/BeerRecommentCustomRepositoryImpl.java
  be/src/main/java/be/domain/recomment/repository/BeerRecommentRepository.java
  be/src/main/java/be/domain/recomment/repository/PairingRecommentCustomRepository.java
  be/src/main/java/be/domain/recomment/repository/PairingRecommentRepository.java
  be/src/main/java/be/domain/recomment/repository/PairingRecommentRepositoryImpl.java
  be/src/main/java/be/domain/recomment/service/BeerRecommentService.java
  be/src/main/java/be/domain/recomment/service/PairingRecommentService.java
  be/src/main/java/be/global/exception/ExceptionCode.java
Labels: feat, 가 빈, refactor, add

#17 GB-26 style:공통컴포넌트 제작(NavBar,SmallCard)
  fe/components/NavBar.tsx
  fe/components/SmallCard.tsx
  fe/components/SmallCardController.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/main/index.tsx
  fe/styles/globals.css
  fe/tsconfig.json
Labels: 안유진, front, style

#16 GB-23 fix: wishlist 매핑 오픈
  be/src/main/java/be/domain/user/entity/Users.java
Labels: back, 서효진, fix

#14 GB-23 feat: MonthlyBeer 연관 패키지 구성
  be/build.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/be/domain/beer/controller/BeerController.java
  be/src/main/java/be/domain/beer/dto/BeerDto.java
  be/src/main/java/be/domain/beer/entity/Beer.java
  be/src/main/java/be/domain/beer/entity/BeerBeerCategory.java
  be/src/main/java/be/domain/beer/entity/BeerBeerTag.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsBasic.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsCounts.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsRatings.java
  be/src/main/java/be/domain/beer/entity/BeerDetailsStars.java
  be/src/main/java/be/domain/beer/entity/MonthlyBeer.java
  be/src/main/java/be/domain/beer/entity/MonthlyBeerBeerCategory.java
  be/src/main/java/be/domain/beer/entity/MonthlyBeerBeerTag.java
  be/src/main/java/be/domain/beer/mapper/BeerMapper.java
  be/src/main/java/be/domain/beer/repository/BeerBeerCategoryQueryRepository.java
  be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java
  be/src/main/java/be/domain/beer/repository/MonthlyBeerQueryRepository.java
  be/src/main/java/be/domain/beer/service/BeerService.java
  be/src/main/java/be/domain/beercategory/entity/BeerCategory.java
  be/src/main/java/be/domain/beertag/dto/BeerTagDto.java
  be/src/main/java/be/domain/beertag/entity/BeerTag.java
  be/src/main/java/be/domain/beertag/repository/BeerTagQueryRepository.java
  be/src/main/java/be/domain/beerwishlist/entity/BeerWishlist.java
  be/src/main/java/be/domain/crawler/SeleniumExecutor.java
  be/src/main/java/be/domain/crawler/TestCrawler.java
  be/src/main/java/be/global/Init.java
  be/src/main/java/be/global/exception/ExceptionCode.java
  be/src/main/java/be/global/init/Init.java
  be/src/main/java/be/global/init/InitConstant.java
  be/src/main/resources/application.yml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/be/controller/BeerControllerRestDocs.java
  be/src/test/java/be/utils/ApiDocumentUtils.java
  be/src/test/java/be/utils/BeerTestConstants.java
Labels: docs, back, 김태영

#18 GB-27 feat: Implement BeerComment CUD
  be/src/main/java/be/domain/comment/controller/BeerCommentController.java
  be/src/main/java/be/domain/comment/dto/BeerCommentDto.java
  be/src/main/java/be/domain/comment/entity/BeerComment.java
  be/src/main/java/be/domain/comment/mapper/BeerCommentMapper.java
  be/src/main/java/be/domain/comment/service/BeerCommentService.java
Labels: back, feat, 가 빈

#22 Fe/style/components/big input
  fe/components/NavBar.tsx
  fe/components/selectBox/PairingBox.tsx
  fe/components/selectBox/SortBox.tsx
  fe/components/smallCards/PopularBeer.tsx
  fe/components/smallCards/PopularBeerController.tsx
  fe/components/smallCards/SimilarBeer.tsx
  fe/components/smallCards/SimilarBeerController.tsx
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/pages/main/Advertise.tsx
  fe/pages/main/index.tsx
  fe/styles/globals.css
  fe/tsconfig.json
Labels: 안유진, front, style
